# Generated by Django 4.0.6 on 2023-07-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
