# Generated by Django 4.0.6 on 2023-07-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_device_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scenario',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Quiz question'), (1, 'Describe the picture'), (2, 'Build a story'), (3, 'Scenario')]),
        ),
    ]
