# Generated by Django 4.0.6 on 2023-08-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_scenario_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='example',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
